name: logly
description: A simple logging tool that uses color coding to indicate severity and offers a clickable link to the printing line.
version: 0.3.1
repository: https://github.com/krista-koivisto/logly

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Dart Logging library.
  logging: ^1.0.1

dev_dependencies:
  test: ^1.17.10
